### ISSUE TITLE
Solutions for each scenario

### ISSUE THREAD

**Issue by allanmoso** [egineering-llc/advanced-git-workshop#6]
It might be useful to document solutions for each of the scenarios that are created.  I'm thinking of maybe creating a separate directory for the solutions.
The solution will probably just be a markdown file.  Name the file according to the Dockerfile name. e.g., `Dockerfile.merge-conflict` will have a solution file named `merge-conflict.md`

**Comment by dbirks** [comment]
I can't quite remember where we left off at the last hackathon. I was also thinking of starting on some tests wired up too. Do you have a preference on folder structure?

### Option 1

A little flat-er, with solutions and tests grouped together:
```
.
├── Dockerfile.common
├── Dockerfile.merge-conflict
├── Dockerfile.push-conflict
├── Dockerfile.split-commit
├── README.md
├── solutions
│   ├── merge-conflict.md
│   ├── push-conflict.md
│   └── split-conflict.md
└── tests
    ├── common.sh
    ├── merge-conflict.sh
    ├── push-conflict.sh
    └── split-commit.sh
```

### Option 2

Grouped more by scenario:
```
.
├── Dockerfile
├── merge-conflict
│   ├── Dockerfile
│   ├── README.md
│   ├── SOLUTION.md
│   └── test.sh
├── push-conflict
│   ├── Dockerfile
│   ├── README.md
│   └── SOLUTION.md
├── README.md
└── split-commit
    ├── Dockerfile
    ├── README.md
    └── SOLUTION.md
```

Or some variation of these, or something completely different?

**Comment by allanmoso** [comment]
Option 2 is what I had in mind.

**Comment by dbirks** [comment]
Ok reorganized like option 2 in this PR: https://github.com/egineering-llc/advanced-git-workshop/pull/19

Going to work on writing up solutions next...
